#!/usr/bin/python3

from pytube import YouTube
import ffmpeg
import os
import sys


yt = YouTube(
        "https://www.youtube.com/watch?v=u2NAuswnTKs",
        #on_progress_callback=progress_func,
        #on_complete_callback=complete_func,
        #proxies=my_proxies,
        use_oauth=True,
        allow_oauth_cache=True
        )

# get audio stream with highest bitrate
stream = yt.streams.get_audio_only()

downloaded_path = stream.download(output_path="/home/sanka/Music/Youtube/", filename=str(yt.title)+".mp3")

input_stream = ffmpeg.input(downloaded_path)
output_stream = input_stream.audio.filter('atrim', start=0, end=258)
output_stream.output("/home/sanka/Music/Youtube/trimmed.mp3").run(overwrite_output=True)

print(downloaded_path)
